### ISSUE TITLE
bulkCollectionUpdate is not defined

### ISSUE THREAD

**Issue by onsombal** [udondan/meteor-bulk-collection-update#2]
Hello, I added bulkCollectionUpdate to my meteor app that's using Meteor 1.0.3.1

The following error messages are returned.
    Exception from Tracker afterFlush function: bulkCollectionUpdate is not defined
    ReferenceError: bulkCollectionUpdate is not defined

I also substituted your example "insert data" code, and I still get these same error messages. 

It doesn't appear that Meteor is recognizing the udondan:bulk-collection-update package that I added and then confirmed via "meteor list".

Any direction you can offer is appreciated.

Thanks... Jim

**Comment by udondan** [comment]
Have you added the call to the code of your server or the client? It looks like I forgot to mention in the readme this module is meant to be used solely on on server side. Currently no client support available.

For the serverside: I just tested it with the most recent version on a new project and can not reproduce any problems.
```
/tmp$ meteor create lala
lala: created.                                

To run your new app:                          
   cd lala
   meteor
/tmp$ cd lala
/tmp$ meteor update

lala: updated to Meteor 1.0.3.1.              
Your packages are at their latest compatible versions.
/tmp$ meteor add udondan:bulk-collection-update
                                                                                   
Changes to your project's package version selections:
                                              
udondan:bulk-collection-update  added, version 0.2.0

                                              
udondan:bulk-collection-update: Bulk insert/update/delete documents in a collection

/tmp$ meteor
[[[[[ /private/tmp/lala ]]]]]                 

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20150212-01:46:42.155(1)? Done. Collection now has 2 documents.
```

Code of my app is the first example from the readme.

**Comment by onsombal** [comment]
Thank you for your quick reply, udondan. I'm still not making progress. I'm
using Papa Parse to import a CSV file. This code works fine. I can display
a portion of the CSV file in an alert statement, and I can display all of
it using console.log. The CSV import is stored in the variable, "data".

I then call a method that resides in on the server-side with
your bulkCollectionUpdate code. If you don't mind, please critique my code:

*client-side code:*

Template.csvImport.rendered = function() {

// Parse local CSV file
  var data;

  function handleFileSelect(evt) {
      var file = evt.target.files[0];
      Papa.parse(file, {
          header: true,
          dynamicTyping: true,

          complete: function(results) {
              data = results;
              alert("data = " + JSON.stringify(data));
              console.log("Finished:", results.data);
          }
      });
  }
    $("#csv-file").change(handleFileSelect);

    Meteor.call('csvImportData', data);
};

*Server-side code*

StrategyQuestions = new Mongo.Collection('strategyQuestions');

Meteor.methods({
    'csvImportData': function(data) {
        var currentUserId = Meteor.userId();
        var user = Meteor.user();

        // bulk insert the data. The field email will be used as primary
identifier for the records
        bulkCollectionUpdate(StrategyQuestions, data, {
            primaryKey: "qNum",
            callback: function() {
                console.log("Done. Collection now has " +
StrategyQuestions.find().count() + " documents.");
                updateData();
            }
        });
    }
});

The error output to the console is below.

 Exception while simulating the effect of invoking 'csvImportData'
ReferenceError: bulkCollectionUpdate is not defined {stack: (...), message:
"bulkCollectionUpdate is not defined"} ReferenceError: bulkCollectionUpdate
is not defined
    at Meteor.methods.csvImportData (
http://localhost:3000/lib/collections/csvImports.js?6f5b272496bcce4a0adc2c38ef9c5f94c1ed56d2:9:9
)
    at
http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:4244:25
    at _.extend.withValue (
http://localhost:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:949:17
)
    at _.extend.apply (
http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:4235:54
)
    at _.extend.call (
http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:4113:17
)
    at Template.csvImport.rendered (
http://localhost:3000/client/templates/csv/csv_import.js?f08380b91eaaf235c6bb8e4dcf0776fbd599f967:26:12
)
    at null.<anonymous> (
http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3008:21
)
    at
http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1733:14
    at Object.Blaze._withCurrentView (
http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12
)
    at
http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1732:15
debug.js:41 Error invoking Method 'csvImportData': Internal server error
[500]



Thoughts?

Thanks... Jim

**Comment by onsombal** [comment]
Hello udondan,

When using your example code, I got the same results as you...

=> I20150212-09:31:07.770(-8)? Done. Collection now has 2 documents.


However, when going to the console, I get the following results:

students.find().fetch()

[]

students.find().count()

0


The count only shows 2 in the terminal window.

Thoughts?


Thanks... Jim

**Comment by udondan** [comment]
Are you subscribed to the collection? Do you see the content when you query the DB on command line via `meteor mongo`?

I currently can not test anything myself. Meteor is broken for me, I can't even create a new project. :-/ https://github.com/meteor/meteor/issues/3714

**Comment by onsombal** [comment]
The subscription was my problem, but I ended up just using collection.insert, which works well for me.

Thank you for your support.

Jim

**Comment by udondan** [comment]
Welcome buddy. Sorry it didn't work for you. Wonder why though, since the package simply [exports the classname](https://github.com/udondan/meteor-bulk-collection-update/blob/master/package.js#L12). That definition then should be globally available on the server. If you'd be still interested in the package the next thing I would suggest is to verify the package was correctly added by checking the package file in the `.meteor` folder. Next thing would be to debug, maybe add a console.log() into the `package.js` to see it gets called.

**Comment by joostf** [comment]
Hi,

I've got the same issue as Jim. 
Installed the package and trying to call bulkCollectionUpdate() from a server method. It's undefined

Any more thoughts on this?
Joost
